"""empty message

Revision ID: 3cdb23fc04b5
Revises: fa69fb3cf1c2
Create Date: 2018-04-25 16:53:13.192939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdb23fc04b5'
down_revision = 'fa69fb3cf1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_mainshow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryid', sa.String(length=16), nullable=True),
    sa.Column('brandname', sa.String(length=100), nullable=True),
    sa.Column('img1', sa.String(length=200), nullable=True),
    sa.Column('childcid1', sa.String(length=16), nullable=True),
    sa.Column('productid1', sa.String(length=16), nullable=True),
    sa.Column('longname1', sa.String(length=200), nullable=True),
    sa.Column('price1', sa.String(length=8), nullable=True),
    sa.Column('marketprice1', sa.Integer(), nullable=True),
    sa.Column('img2', sa.String(length=200), nullable=True),
    sa.Column('childcid2', sa.String(length=16), nullable=True),
    sa.Column('productid2', sa.String(length=16), nullable=True),
    sa.Column('longname2', sa.String(length=200), nullable=True),
    sa.Column('price2', sa.String(length=8), nullable=True),
    sa.Column('marketprice2', sa.Integer(), nullable=True),
    sa.Column('img3', sa.String(length=200), nullable=True),
    sa.Column('childcid3', sa.String(length=16), nullable=True),
    sa.Column('productid3', sa.String(length=16), nullable=True),
    sa.Column('longname3', sa.String(length=200), nullable=True),
    sa.Column('price3', sa.String(length=8), nullable=True),
    sa.Column('marketprice3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('axf_mainshow')
    # ### end Alembic commands ###
