"""empty message

Revision ID: 52149dfbd741
Revises: 7793062626ff
Create Date: 2018-04-25 14:22:39.159361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52149dfbd741'
down_revision = '7793062626ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_mustbuy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('axf_mustbuy')
    # ### end Alembic commands ###
