"""empty message

Revision ID: a0131047ddad
Revises: 3cdb23fc04b5
Create Date: 2018-04-25 16:55:40.008022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0131047ddad'
down_revision = '3cdb23fc04b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('axf_mainshow', sa.Column('trackid', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('axf_mainshow', 'trackid')
    # ### end Alembic commands ###
