"""empty message

Revision ID: fa69fb3cf1c2
Revises: 52149dfbd741
Create Date: 2018-04-25 15:39:56.041359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa69fb3cf1c2'
down_revision = '52149dfbd741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('axf_shop')
    # ### end Alembic commands ###
